<template>
  <div class="min-h-screen bg-slate-50 text-slate-700 text-[13px]"><div class="mx-auto max-w-[1200px] p-4 sm:p-5">
    <div class="mb-4 flex items-center justify-between border-b border-slate-200 pb-4"><div class="flex items-center gap-3"><button @click="$router.back()" class="h-8 w-8 border border-slate-200 bg-white"><i class="fas fa-arrow-left text-xs"></i></button><div><p class="text-[10px] uppercase tracking-wider text-slate-400">Channel Growth</p><h1 class="text-lg font-bold">{{item?.name||"Growth Details"}}</h1></div></div><button v-if="item" @click="showEdit=true" class="h-9 bg-primary px-4 text-xs font-semibold text-white">Edit</button></div>
    <div v-if="loading" class="bg-white p-10 text-center text-xs text-slate-400">Loading...</div><div v-else-if="item" class="grid grid-cols-1 gap-4 lg:grid-cols-3">
      <div class="overflow-hidden border border-slate-200 bg-white"><div class="aspect-square bg-slate-100"><img v-if="getThumbnailUrl(item)" :src="getThumbnailUrl(item)" :alt="item.name" class="h-full w-full object-cover"/><div v-else class="flex h-full items-center justify-center text-slate-300"><i class="fas fa-chart-line text-4xl"></i></div></div><div class="p-4"><p class="text-[9px] uppercase text-slate-400">Price</p><p class="text-2xl font-bold">{{formatPrice(item.price)}} {{item.currency||"USD"}}</p></div></div>
      <div class="lg:col-span-2 border border-slate-200 bg-white"><div class="border-b border-slate-100 p-4"><div class="flex gap-2"><span class="badge">{{item.type||"Growth"}}</span><span class="badge">{{item.slug||"-"}}</span></div><h2 class="mt-3 text-base font-bold">{{item.name}}</h2><p class="mt-2 whitespace-pre-line text-xs leading-6 text-slate-600">{{item.description||"No description available."}}</p></div><div class="p-4"><p class="label">Details</p><pre class="whitespace-pre-wrap break-words bg-slate-50 p-3 text-xs text-slate-600">{{formatDetails(item.details)}}</pre></div><div v-if="files.length" class="border-t border-slate-100 p-4"><p class="label">Files</p><ul class="mt-2 space-y-1"><li v-for="(f,i) in files" :key="i" class="bg-slate-50 p-2 text-xs">{{getFileName(f)}}</li></ul></div></div>
    </div><div v-else class="bg-white p-10 text-center text-xs text-slate-500">Channel Growth record not found.</div>
    <EditGrowth v-if="showEdit" :data="item" @close="showEdit=false" @saved="showEdit=false;fetchGrowth()"/>
  </div></div>
</template>
<script>
import EditGrowth from "./EditGrowth.vue";
export default {name:"DetailGrowth",components:{EditGrowth},data(){return{item:null,files:[],loading:false,showEdit:false};},methods:{
async fetchGrowth(){this.loading=true;try{const r=await this.$apiGet(`/growth/${this.$route.params.id}`);const p=r?.data||r;this.item=p?.data||p;this.files=Array.isArray(this.item?.files)?this.item.files:[];}catch(e){console.error(e);this.showToast(e?.response?.data?.message||"Failed to load Channel Growth","error")}finally{this.loading=false}},
getThumbnailUrl(i){const m=i?.thumbnail;if(!m)return null;if(typeof m==="string")return m;return m.url||m.path||m.src||m.location||m.fileUrl||null},formatPrice(v){const n=Number(v);return Number.isNaN(n)?"0.00":n.toFixed(2)},formatDetails(d){if(!d)return "{}";if(typeof d==="string"){try{return JSON.stringify(JSON.parse(d),null,2)}catch{return d}}return JSON.stringify(d,null,2)},getFileName(f){if(typeof f==="string")return f.split("/").pop();return f?.name||f?.filename||f?.originalname||f?.url||"File"},showToast(m,t){if(this.$root?.$refs?.toast)this.$root.$refs.toast.showToast(m,t)}},mounted(){this.fetchGrowth()}}
</script>
<style scoped>
.badge{@apply bg-slate-100 px-2 py-1 text-[9px] font-semibold text-slate-600}.label{@apply mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-400}
</style>